# my new items
markdown: kramdown
#markdown: redcarpet
redcarpet:
    extensions: ["tables"] 
permalink: /:year/:month/:title 
github: nwf5d
duoshuo: nwf5d
email: nwfengwolf@gmail.com
#url: http://nwf5d.net
#url: http://nwf5d.github.io
url: localhost:4000
name: Richard Nieh
author: Richard Nieh
img_url: http://nwf5d.github.com/assets/images
code_dir: /assets/code
weibo: 745689147

pygments: true
safe: true
paginate: 20
